from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path


PRIMARY_POLICY_PATH = Path("/app/workspace/policy/assets/site_policy.json")


@dataclass(frozen=True)
class AuditFinding:
    kind: str
    algorithm: str
    compliant: bool
    reason: str


FAMILY_PREFIXES = {
    "kex": (
        "curve25519-",
        "diffie-hellman-group14-",
        "ecdh-sha2-",
    ),
    "ciphers": (
        "chacha20-",
        "aes128-ctr",
        "aes192-ctr",
        "aes256-",
    ),
    "macs": (
        "hmac-sha2-",
        "hmac-sha1",
        "umac-128",
    ),
}


WEAK_ALGORITHMS = {
    "kex": {
        "diffie-hellman-group1-sha1": "1024-bit group with SHA-1 is obsolete",
        "diffie-hellman-group14-sha1": "SHA-1 based key exchange is deprecated",
    },
    "ciphers": {
        "3des-cbc": "CBC mode and short block size are weak",
        "aes256-cbc": "CBC mode is not allowed in this policy",
    },
    "macs": {
        "hmac-md5": "MD5 based MAC is weak",
        "hmac-sha1": "SHA-1 MAC is deprecated",
    },
}


def load_site_policy(path: str | Path = PRIMARY_POLICY_PATH) -> dict:
    with Path(path).open("r", encoding="utf-8") as handle:
        return json.load(handle)


def _is_compliant(kind: str, algorithm: str) -> bool:
    for prefix in FAMILY_PREFIXES[kind]:
        if algorithm.startswith(prefix):
            return True
    return False


def audit_algorithms(policy: dict) -> list[AuditFinding]:
    findings: list[AuditFinding] = []
    for kind, algorithms in policy["algorithms"].items():
        weak = WEAK_ALGORITHMS[kind]
        for algorithm in algorithms:
            compliant = _is_compliant(kind, algorithm)
            findings.append(
                AuditFinding(
                    kind=kind,
                    algorithm=algorithm,
                    compliant=compliant,
                    reason=weak.get(algorithm, "allowed by policy family"),
                )
            )
    return findings


def render_sshd_config(policy: dict) -> str:
    findings = audit_algorithms(policy)
    allowed_by_kind: dict[str, list[str]] = {"kex": [], "ciphers": [], "macs": []}
    for finding in findings:
        if finding.compliant:
            allowed_by_kind[finding.kind].append(finding.algorithm)

    lines = [
        "# Generated by branch-edge-west SSH policy",
        f"Port {policy['service']['port']}",
        f"ListenAddress {policy['service']['listen_address']}",
        f"KexAlgorithms {','.join(allowed_by_kind['kex'])}",
        f"Ciphers {','.join(allowed_by_kind['ciphers'])}",
        f"MACs {','.join(allowed_by_kind['macs'])}",
    ]
    return "\n".join(lines) + "\n"


def build_audit_report(path: str | Path = PRIMARY_POLICY_PATH) -> dict:
    policy = load_site_policy(path)
    findings = audit_algorithms(policy)
    return {
        "site": policy["site"],
        "findings": [
            {
                "kind": finding.kind,
                "algorithm": finding.algorithm,
                "compliant": finding.compliant,
                "reason": finding.reason,
            }
            for finding in findings
        ],
        "config": render_sshd_config(policy),
    }


if __name__ == "__main__":
    print(json.dumps(build_audit_report(), indent=2))
