(define (problem dawn-relay-gamma)
  (:domain observatory-night)
  (:objects
    scope1 - telescope
    park att-atlas att-deneb att-foramen att-hydra relay - attitude
    atlas deneb foramen hydra - target
    s0 s1 s2 s3 s4 s5 s6 s7 s8 s9 s10 s11 s12 s13 s14 s15 s16 s17 s18 s19 s20 - slot)

  (:init
    (current-attitude scope1 park)
    (stable scope1)
    (buffer-free scope1)
    (slew-link park att-atlas)
    (slew-link att-atlas relay)
    (slew-link relay att-deneb)
    (slew-link att-deneb relay)
    (slew-link relay att-foramen)
    (slew-link att-foramen relay)
    (slew-link relay att-hydra)
    (slew-link att-hydra relay)
    (points-at att-atlas atlas)
    (points-at att-deneb deneb)
    (points-at att-foramen foramen)
    (points-at att-hydra hydra)
    (relay-attitude relay)
    (requested atlas)
    (requested deneb)
    (requested foramen)
    (requested hydra)
    (target-visible atlas s2)
    (target-visible deneb s7)
    (target-visible foramen s12)
    (target-visible hydra s17)
    (link-visible s4)
    (link-visible s9)
    (link-visible s14)
    (link-visible s19)
    (current-slot s0)
    (next-slot s1 s0)
    (next-slot s2 s1)
    (next-slot s3 s2)
    (next-slot s4 s3)
    (next-slot s5 s4)
    (next-slot s6 s5)
    (next-slot s7 s6)
    (next-slot s8 s7)
    (next-slot s9 s8)
    (next-slot s10 s9)
    (next-slot s11 s10)
    (next-slot s12 s11)
    (next-slot s13 s12)
    (next-slot s14 s13)
    (next-slot s15 s14)
    (next-slot s16 s15)
    (next-slot s17 s16)
    (next-slot s18 s17)
    (next-slot s19 s18)
    (next-slot s20 s19))

  (:goal (and
    (sent atlas)
    (sent deneb)
    (sent foramen)
    (sent hydra)))
)
