(define (problem southern-arc-beta)
  (:domain observatory-night)
  (:objects
    scope1 - telescope
    park att-pegasus att-vela att-scorpius relay - attitude
    pegasus vela scorpius - target
    s0 s1 s2 s3 s4 s5 s6 s7 s8 s9 s10 s11 s12 s13 s14 s15 - slot)

  (:init
    (current-attitude scope1 park)
    (stable scope1)
    (buffer-free scope1)
    (slew-link park att-pegasus)
    (slew-link att-pegasus relay)
    (slew-link relay att-vela)
    (slew-link att-vela relay)
    (slew-link relay att-scorpius)
    (slew-link att-scorpius relay)
    (points-at att-pegasus pegasus)
    (points-at att-vela vela)
    (points-at att-scorpius scorpius)
    (relay-attitude relay)
    (requested pegasus)
    (requested vela)
    (requested scorpius)
    (target-visible pegasus s2)
    (target-visible vela s7)
    (target-visible scorpius s12)
    (link-visible s4)
    (link-visible s9)
    (link-visible s14)
    (current-slot s0)
    (next-slot s1 s0)
    (next-slot s2 s1)
    (next-slot s3 s2)
    (next-slot s4 s3)
    (next-slot s5 s4)
    (next-slot s6 s5)
    (next-slot s7 s6)
    (next-slot s8 s7)
    (next-slot s9 s8)
    (next-slot s10 s9)
    (next-slot s11 s10)
    (next-slot s12 s11)
    (next-slot s13 s12)
    (next-slot s14 s13)
    (next-slot s15 s14))

  (:goal (and
    (sent pegasus)
    (sent vela)
    (sent scorpius)))
)
