#!/bin/bash
set -euo pipefail

cat <<'EOF' > /app/workspace/policy/renderers/sshd_policy.py
from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path


PRIMARY_POLICY_PATH = Path("/app/workspace/policy/assets/site_policy.json")


@dataclass(frozen=True)
class AuditFinding:
    kind: str
    algorithm: str
    compliant: bool
    reason: str


ALLOWED_ALGORITHMS = {
    "kex": {
        "curve25519-sha256",
        "diffie-hellman-group14-sha256",
        "ecdh-sha2-nistp256",
    },
    "ciphers": {
        "chacha20-poly1305@openssh.com",
        "aes256-gcm@openssh.com",
        "aes128-ctr",
        "aes192-ctr",
        "aes256-ctr",
    },
    "macs": {
        "hmac-sha2-256",
        "hmac-sha2-512-etm@openssh.com",
        "umac-128-etm@openssh.com",
    },
}


WEAK_ALGORITHMS = {
    "kex": {
        "diffie-hellman-group1-sha1": "1024-bit group with SHA-1 is obsolete",
        "diffie-hellman-group14-sha1": "SHA-1 based key exchange is deprecated",
    },
    "ciphers": {
        "3des-cbc": "CBC mode and short block size are weak",
        "aes256-cbc": "CBC mode is not allowed in this policy",
    },
    "macs": {
        "hmac-md5": "MD5 based MAC is weak",
        "hmac-sha1": "SHA-1 MAC is deprecated",
    },
}


def load_site_policy(path: str | Path = PRIMARY_POLICY_PATH) -> dict:
    with Path(path).open("r", encoding="utf-8") as handle:
        return json.load(handle)


def _finding_reason(kind: str, algorithm: str, compliant: bool) -> str:
    weak_reason = WEAK_ALGORITHMS[kind].get(algorithm)
    if weak_reason is not None:
        return weak_reason
    if compliant:
        return "allowed by hardened policy"
    return "algorithm is outside the allowed baseline"


def _is_compliant(kind: str, algorithm: str) -> bool:
    return algorithm in ALLOWED_ALGORITHMS[kind]


def audit_algorithms(policy: dict) -> list[AuditFinding]:
    findings: list[AuditFinding] = []
    for kind, algorithms in policy["algorithms"].items():
        for algorithm in algorithms:
            compliant = _is_compliant(kind, algorithm)
            findings.append(
                AuditFinding(
                    kind=kind,
                    algorithm=algorithm,
                    compliant=compliant,
                    reason=_finding_reason(kind, algorithm, compliant),
                )
            )
    return findings


def render_sshd_config(policy: dict) -> str:
    findings = audit_algorithms(policy)
    allowed_by_kind: dict[str, list[str]] = {"kex": [], "ciphers": [], "macs": []}
    for finding in findings:
        if finding.compliant:
            allowed_by_kind[finding.kind].append(finding.algorithm)

    lines = [
        "# Generated by branch-edge-west SSH policy",
        f"Port {policy['service']['port']}",
        f"ListenAddress {policy['service']['listen_address']}",
        f"KexAlgorithms {','.join(allowed_by_kind['kex'])}",
        f"Ciphers {','.join(allowed_by_kind['ciphers'])}",
        f"MACs {','.join(allowed_by_kind['macs'])}",
    ]
    return "\n".join(lines) + "\n"


def build_audit_report(path: str | Path = PRIMARY_POLICY_PATH) -> dict:
    policy = load_site_policy(path)
    findings = audit_algorithms(policy)
    return {
        "site": policy["site"],
        "findings": [
            {
                "kind": finding.kind,
                "algorithm": finding.algorithm,
                "compliant": finding.compliant,
                "reason": finding.reason,
            }
            for finding in findings
        ],
        "config": render_sshd_config(policy),
    }


if __name__ == "__main__":
    print(json.dumps(build_audit_report(), indent=2))
EOF
